#ifndef ENUMS_H_
#define ENUMS_H_

enum GamePieceType
{
	GAME_PIECE_KING,
	GAME_PIECE_QUEEN,
	GAME_PIECE_BISHOP,
	GAME_PIECE_KNIGHT,
	GAME_PIECE_ROOK,
	GAME_PIECE_PAWN,
	GAME_PIECE_COUNT,
};

enum Player
{
	PLAYER_WHITE,
	PLAYER_BLACK,
	PLAYER_COUNT,
};

enum ColorCode
{
	COLOR_FORE_BLACK = 30,
	COLOR_FORE_WHITE = 37,
	COLOR_BACK_BLACK = 40,
	COLOR_BACK_WHITE = 47,
	COLOR_FORE_BRIGHT_BLACK = 90,
	COLOR_FORE_BRIGHT_WHITE = 97,
	COLOR_BACK_BRIGHT_BLACK = 100,
	COLOR_BACK_BRIGHT_WHITE = 107,
};

#endif /* ENUMS_H_ */